# Generated by Django 3.1.6 on 2022-02-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20220221_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='time',
        ),
    ]
