# Generated by Django 3.1.6 on 2022-04-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_auto_20220427_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Xacceleration',
            new_name='X_acceleration',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Xgyroscope',
            new_name='X_gyroscope',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Yacceleration',
            new_name='Y_acceleration',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Ygyroscope',
            new_name='Y_gyroscope',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Zacceleration',
            new_name='Z_acceleration',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Zgyroscope',
            new_name='Z_gyroscope',
        ),
    ]
